# Generated by Django 5.0.6 on 2024-06-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0009_rename_likes_message_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='like',
            new_name='likes',
        ),
    ]
