# Generated by Django 5.0.6 on 2024-06-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='post_date',
            new_name='created_at',
        ),
    ]
