# Generated by Django 5.0.6 on 2024-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0006_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
