# Generated by Django 5.0.6 on 2024-06-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0008_message_likes_alter_message_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='likes',
            new_name='like',
        ),
    ]
