# Generated by Django 5.0.6 on 2024-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0010_rename_like_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='app_social_media.profile'),
        ),
    ]
