# Generated by Django 5.0.6 on 2024-06-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0011_alter_message_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
